### ISSUE TITLE
New Action Handler: Helm Describe

### ISSUE THREAD

**Issue by vlad-tkachenko** [apigeeks-com/a6s-fbl-k8s-plugin#10]
Please add new action handler that allows to describe helm resources.

**ID:** a6s.k8s.helm.describe

**Aliases:**
- k8s.helm.describe
- helm.describe

```yaml
helm.describe:
  # [required] helm chart release name
  name: ftpo
  # [optional] define paths to store chart information (https://github.com/apigeeks-com/a6s-fbl-k8s-plugin/blob/master/src/services/K8sHelmService.ts)
  chart: 
    assignTo: '$.ctx.chart'
    pushTo: '$.ctx.chart'
  # [optional] define paths to store helm k8s objects (https://github.com/apigeeks-com/a6s-fbl-k8s-plugin/blob/master/src/services/K8sHelmService.ts#L180)  
  objects:
    assignTo: '$.ctx.chart'
    pushTo: '$.ctx.chart'
```
