### ISSUE TITLE
New Action Handler: Kubectl Delete

### ISSUE THREAD

**Issue by vlad-tkachenko** [apigeeks-com/a6s-fbl-k8s-plugin#2]
Additionally to kubectl apply action handler add ability to remove objects.

```yaml
kubectl.delete:
  # required
  kind: Secret 
  # required
  name: some-secret
  # optional
  namespace: default
```
