### ISSUE TITLE
New action handler: k8s bulk delete

### ISSUE THREAD

**Issue by vlad-tkachenko** [apigeeks-com/a6s-fbl-k8s-plugin#9]
Please add new action handler that can make bulk removal of any K8s Objects by name masks in a given namespace.

**ID:** a6s.k8s.kubectl.delete.bulk

**Aliases:**
- k8s.kubectl.delete.bulk
- kubectl.delete.bulk

```yaml
kubectl.delete.bulk:
  # [required] K8s Object kind
  kind: Secret
  # [optional] Namespace to delete the objects in.
  # Default value: default
  namespace: ci
  # [required] List of names and/or masks of the objects to remove
  names:
   - 'test-*'
   - 'ftpo-*'
```
